name: release_tools
description: A collection of scripts to help with creating releases and publishing libraries.
version: 1.0.0
homepage: https://github.com/asartalo/release_tools

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ansicolor: ^2.0.2
  args: ^2.4.2
  conventional: ^0.4.0
  equatable: ^2.0.5
  file: ^7.0.0
  pub_semver: ^2.1.4
  yaml: ^3.1.2

dev_dependencies:
  coverage: ^1.7.1
  # git_hooks: ^2.0.0 # use this when null-safe version is officially available
  git_hooks: ^1.0.1
  lint: ^2.2.0
  test: ^1.24.9

executables:
  release_tools:
