name: release_tools
description: A collection of scripts to help with creating releases and publishing libraries.
version: 0.2.4
homepage: https://github.com/asartalo/release_tools

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ansicolor: ^2.0.1
  args: ^2.0.0
  conventional: ^0.3.0
  equatable: ^2.0.0
  file: ^6.1.0
  pub_semver: ^2.0.0
  yaml: ^3.1.0

dev_dependencies:
  coverage: ^1.0.1
  # git_hooks: ^2.0.0 # use this when null-safe version is officially available
  git_hooks:
    git:
      url: https://github.com/asartalo/git_hooks.git
      ref: null-safety-2
  lint: ^1.5.3
  test: ^1.14.4

executables:
  release_tools:
