name: build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v2

  test:
    name: Tests
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    needs: commitlint
    outputs:
      branch: ${{ steps.branchinfo.outputs.branch }}

    steps:

    - uses: nelonoel/branch-name@v1.0.1
    # Use branch name for whatever purpose
    - name: Store the branch name
    - id: branchinfo
      run: echo "::set-output name=branch::${BRANCH_NAME}"

    - name: Check if we were able to save branch info
      run: echo ${{ steps.branchinfo.outputs.branch }}

    - uses: cedx/setup-dart@v2
      with:
        release-channel: stable

    # Checkout
    - uses: actions/checkout@v2

    - name: Get dependencies
      run: pub get

    - name: Check dart formatting
      run: dart format --set-exit-if-changed .

    - name: Statically analyze the Dart code for any errors.
      run: dart analyze .

    - name: Run Tests with coverage
      run: dart test --coverage="coverage"

    - name: Prepare coverage
      run: pub run coverage:format_coverage --lcov --in=coverage --out=lcov.info --packages=.packages --report-on=lib

    - name: Upload coverage
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: lcov.info

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: ${{ needs.test.outputs.branch == 'main' }}

    steps:
    - run: echo ${{ needs.test.outputs.branch }}
