name: Publish to pub.dev

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+" # tag pattern on pub.dev: 'v'

# Publish using custom workflow
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check tag
        run: echo "${{ github.ref_name }}"

  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
